#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
env.Append(CPPPATH=["src/tinycc-mob"])

env.Append(CPPDEFINES=[
    "ONE_SOURCE", 
    "TCC_TARGET_X86_64"
])

if env["platform"] == "linux":
    env.Append(LIBPATH=["src/tinycc-mob/lib"])
    env.Append(LIBS=["tcc1"])
elif env["platform"] == "windows":
    env.Append(CPPDEFINES=["TCC_TARGET_PE"])

sources = Glob("src/*.cpp")
sources.append("src/tinycc-mob/libtcc.c")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "demo/bin/libgdtinycc.{}.{}.framework/libgdtinycc.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "demo/bin/libgdtinycc{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
